import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";
import test from "node:test";

import { evaluate } from "../src/decision.js";
import { isTampering } from "../src/errors.js";
import { type Claims, publicKeyFromBase64, verifyWithKeys } from "../src/licensefile.js";

/**
 * The conformance suite. Every Licencly SDK runs this same file, which is what
 * keeps four independent implementations from drifting apart: a vendor
 * switching from Go to TypeScript must get identical answers.
 *
 * testdata/vectors.json is generated by the server repo. Do not edit it here.
 */

interface Vector {
  name: string;
  description: string;
  file: string;
  public_keys: Record<string, string>;
  fingerprint: string;
  now: number;
  expect: string;
  needs_revalidation: boolean;
  maintenance_active: boolean;
}

const here = dirname(fileURLToPath(import.meta.url));
const vectorsPath = join(here, "..", "..", "testdata", "vectors.json");

const vectors: Vector[] = JSON.parse(readFileSync(vectorsPath, "utf8")).vectors;

assert.ok(vectors.length > 0, "vectors.json is empty");

function keysFor(v: Vector): Map<string, ReturnType<typeof publicKeyFromBase64>> {
  return new Map(Object.entries(v.public_keys).map(([kid, k]) => [kid, publicKeyFromBase64(k)]));
}

for (const v of vectors) {
  test(`conformance: ${v.name}`, () => {
    const now = new Date(v.now * 1000);

    let claims: Claims | undefined;
    let error: unknown;
    try {
      claims = verifyWithKeys(v.file, keysFor(v));
    } catch (err) {
      error = err;
    }

    const decision = evaluate(claims, error, now, v.fingerprint, false);

    assert.equal(decision.outcome, v.expect, `${v.name}: ${v.description}`);

    if (v.expect !== "valid") return;

    assert.equal(decision.needsRevalidation, v.needs_revalidation, "needs_revalidation");
    assert.equal(decision.maintenanceActive, v.maintenance_active, "maintenance_active");
  });
}

test("tampering is never reported as retryable", () => {
  for (const v of vectors.filter((x) => x.expect === "invalid")) {
    let error: unknown;
    try {
      verifyWithKeys(v.file, keysFor(v));
    } catch (err) {
      error = err;
    }

    assert.ok(error, `${v.name}: a vector expecting invalid verified successfully`);
    // A client that retries a forged file hides an attack behind what looks
    // like a flaky network.
    assert.ok(isTampering(error), `${v.name}: not reported as tampering, so callers will retry`);
  }
});

test("vectors cover every outcome", () => {
  const seen = new Set(vectors.map((v) => v.expect));

  for (const outcome of ["valid", "invalid", "not_active", "expired", "wrong_machine", "stale"]) {
    assert.ok(seen.has(outcome), `no vector expects ${outcome}`);
  }
});
